#
# This is the default Travis CI configuration.
#
# It uses a GitHub OAuth token when fetching composer dependencies
# to avoid IP-based API throttling.
#
# It also allows publication of artifacts via an additional build.
#
language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.4
    - secure: "qKf1GMFUMC1zEnQRmnHq6yyTDkbVlO+IOhyDgdraM/Ba3zgoKLw/6222/aZkag+XWYKTxbnZ7BVk8yT81AVqzt4REav3bbsKOr53GCcP5IMKZ2ynbBICaURewlk1hvMviFl3g4kqnj8bjWgnq0NaOIQT7pT390jvtIXvMRNtuhI="

install:
  - ./.travis.install
script:
  - ./vendor/bin/archer travis:build
  - [[ $TRAVIS_PHP_VERSION == $ARCHER_PUBLISH_VERSION ]] && ./vendor/bin/coveralls
